apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: im-message
  namespace: im
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: im-message
  minReplicas: 3
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
