apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: im-user
  namespace: im
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: im-user
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
